# The user to run nginx
nginx_user: "www-data"

nginx_sites:
  server:
     - listen 0.0.0.0:80
     - server_name ML-Infra
     - access_log /var/log/nginx/ML-Infra.log
     - location / { proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Host $http_host; proxy_set_header X-NginX-Proxy true; proxy_pass http://127.0.0.1:8080; proxy_redirect off;}
  
nginx_configs:
  upstream:
      - upstream nodejs { server 127.0.0.1:8080 weight=10; }