---
- hosts: all

  sudo: True

  vars_files:
    - vars/nginx.yml
    # - vars/users.yml

  roles:
    # - role: ANXS.generic-users
    #   tag: users

    - role: jdauphant.nginx
      tag: nginx

    # - role: ANXS.build-essential
    #   tag: buildessential


  # pre_tasks:
  #   - name: Run the equivalent of "apt-get update" as a separate step
  #     apt:
  #       update_cache: yes

  #   - name: Update all packages to the latest version
  #     apt:
  #       upgrade: dist

  #   - name: Ensure sudo group can use sudo without password
  #     lineinfile:
  #       dest: /etc/sudoers
  #       state: present
  #       regexp: '^%sudo'
  #       line: '%sudo ALL=(ALL) NOPASSWD: ALL'
  #       validate: visudo -cf %s
  #   - shell: sudo chown -R emile:root /home/ML-Infra

  tasks:
    - name: Install list of packages
      apt: name="{{item}}" state=installed
      with_items:
            - git
            - python3-pip
            - python3-venv
            - nodejs
            - npm
            - nodejs-legacy
            - sqlite3


    - name: Install pm2 globally
      npm: name=pm2 global=yes

    - script: venv_fix.sh

    - name: Install requirements
      pip: 
        name: Flask==0.12, flask-cors, numpy==1.12, pandas==0.19.2, scikit-learn==0.18.1, scipy==0.18.1, gunicorn
        # requirements: ../../requirements.txt
        virtualenv: /home/venvs/myenv
        virtualenv_python: python3.5

    - name: Clean cron path
      file:
        state: absent
        path: /etc/cron.d/ansible_auto_train

    - name: train model
      cron:
        name: train_model
        job: curl -H -X GET http://127.0.0.1/train
        cron_file: ansible_auto_train
        user: ubuntu
